import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { getuser } from '@/lib/getuser';
type User = {
  id: string;
  name: string;
  email: string;
};
export const metadata: Metadata = {
  title: "JobHawk || Pricing",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getuser(); // Fetch session data
  const user: User | undefined = session?.user
  ? {
      id: session.user.id || '', // Ensure id is a string
      name: session.user.name || 'Unknown', // Provide a fallback for name
      email: session.user.email || '', // Ensure email is a string
    }
  : undefined;
  return (
    <>
        {children}
    </>
  );
}
