import type { Metadata } from "next";
import { getuser } from "@/lib/getuser";
import { redirect } from "next/navigation";
import ProfileNavbar from "@/components/ProfileNavbar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "JobHawk || Profile",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const session = await getuser(); // Fetch session data
   if(session==null){
    redirect("/login");
   }
  return (
 
    <>
        <ProfileNavbar userImage={session.user?.image} />
        {children}
        <Footer/>
    </>
  );
}
